# Generated by Django 5.0.7 on 2024-07-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='a_pic',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='director',
            name='d_pic',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to='photos/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='u_dp',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
